### ISSUE TITLE
forge not finding existing branch

### ISSUE THREAD

**Issue by mtps** [provenance-io/forge.pb#9]
## Summary of Bug

Expected command `forge node start --provenance-branch release/1.7.x` to fetch and build that version, however, getting result of `The entered branch, release/1.7.x, does not exist.`. The branch exists in github.

## Version

v1.0.1 from pip

## Steps to Reproduce

Run `forge node start --provenance-branch release/1.7.x`
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by wbaker-figure** [comment]
Fixed on commit [221f79a4940aa63adcf315be36432819f7b738ab](https://github.com/provenance-io/forge.pb/commit/221f79a4940aa63adcf315be36432819f7b738ab)
